// <auto-generated />
namespace AutoVentas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_AUTOVENTAS_CARS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_AUTOVENTAS_CARS));
        
        string IMigrationMetadata.Id
        {
            get { return "201604150835432_DB_AUTOVENTAS_CARS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
